Name: Kai Chung, Ying

Class: CSC 478 Assignment #3

Date: 11/02/2017

####1a) Load and preprocess the data using Pandas or Numpy and, if necessary, preprocessing functions from scikit-learn. The provided data is already normalized (see description), so there is no need for additional normalization. Compute and display basic statistics (mean, standard deviation, min, max, etc.) for each of the variables in the data set. Separate the target attribute for regression.

In [285]:
import pandas as pd
import numpy as np
from numpy import *

In [251]:
#Read the dataset
ccData=pd.read_csv('./communities/communities.csv')

In [252]:
ccData.shape

(1994, 100)

In [253]:
ccData.head(5)

state        communityname  population  householdsize  racepctblack  \
0      8         Lakewoodcity        0.19           0.33          0.02   
1     53          Tukwilacity        0.00           0.16          0.12   
2     24         Aberdeentown        0.00           0.42          0.49   
3     34  Willingborotownship        0.04           0.77          1.00   
4     42    Bethlehemtownship        0.01           0.55          0.02   

   racePctWhite  racePctAsian  racePctHisp  agePct12t21  agePct12t29  \
0          0.90          0.12         0.17         0.34         0.47   
1          0.74          0.45         0.07         0.26         0.59   
2          0.56          0.17         0.04         0.39         0.47   
3          0.08          0.12         0.10         0.51         0.50   
4          0.95          0.09         0.05         0.38         0.38   

          ...           NumStreet  PctForeignBorn  PctBornSameState  \
0         ...                 0.0            0.12              0.42   
1         ...                 0.0            0.21              0.50   
2         ...                 0.0            0.14              0.49   
3         ...                 0.0            0.19              0.30   
4         ...                 0.0            0.11              0.72   

   PctSameHouse85  PctSameCity85  PctSameState85  LandArea  PopDens  \
0            0.50           0.51            0.64      0.12     0.26   
1            0.34           0.60            0.52      0.02     0.12   
2            0.54           0.67            0.56      0.01     0.21   
3            0.73           0.64            0.65      0.02     0.39   
4            0.64           0.61            0.53      0.04     0.09   

   PctUsePubTrans  ViolentCrimesPerPop  
0            0.20                 0.20  
1            0.45                 0.67  
2            0.02                 0.43  
3            0.28                 0.12  
4            0.02                 0.03  

[5 rows x 100 columns]

In [254]:
#Check if there is any missing values in every Column
missTab=ccData.isnull().sum(0)
missTab[missTab.ix[:]>0]

Series([], dtype: int64)

Based on the above, there is NO missing values.

In [255]:
#Show the Statistics of the dataset
ccData.describe()

state   population  householdsize  racepctblack  racePctWhite  \
count  1994.000000  1994.000000    1994.000000   1994.000000   1994.000000   
mean     28.683551     0.057593       0.463395      0.179629      0.753716   
std      16.397553     0.126906       0.163717      0.253442      0.244039   
min       1.000000     0.000000       0.000000      0.000000      0.000000   
25%      12.000000     0.010000       0.350000      0.020000      0.630000   
50%      34.000000     0.020000       0.440000      0.060000      0.850000   
75%      42.000000     0.050000       0.540000      0.230000      0.940000   
max      56.000000     1.000000       1.000000      1.000000      1.000000   

       racePctAsian  racePctHisp  agePct12t21  agePct12t29  agePct16t24  \
count   1994.000000  1994.000000  1994.000000  1994.000000  1994.000000   
mean       0.153681     0.144022     0.424218     0.493867     0.336264   
std        0.208877     0.232492     0.155196     0.143564     0.166505   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%        0.040000     0.010000     0.340000     0.410000     0.250000   
50%        0.070000     0.040000     0.400000     0.480000     0.290000   
75%        0.170000     0.160000     0.470000     0.540000     0.360000   
max        1.000000     1.000000     1.000000     1.000000     1.000000   

              ...             NumStreet  PctForeignBorn  PctBornSameState  \
count         ...           1994.000000     1994.000000       1994.000000   
mean          ...              0.022778        0.215552          0.608892   
std           ...              0.100400        0.231134          0.204329   
min           ...              0.000000        0.000000          0.000000   
25%           ...              0.000000        0.060000          0.470000   
50%           ...              0.000000        0.130000          0.630000   
75%           ...              0.000000        0.280000          0.777500   
max           ...              1.000000        1.000000          1.000000   

       PctSameHouse85  PctSameCity85  PctSameState85     LandArea  \
count     1994.000000    1994.000000     1994.000000  1994.000000   
mean         0.535050       0.626424        0.651530     0.065231   
std          0.181352       0.200521        0.198221     0.109459   
min          0.000000       0.000000        0.000000     0.000000   
25%          0.420000       0.520000        0.560000     0.020000   
50%          0.540000       0.670000        0.700000     0.040000   
75%          0.660000       0.770000        0.790000     0.070000   
max          1.000000       1.000000        1.000000     1.000000   

           PopDens  PctUsePubTrans  ViolentCrimesPerPop  
count  1994.000000     1994.000000          1994.000000  
mean      0.232854        0.161685             0.237979  
std       0.203092        0.229055             0.232985  
min       0.000000        0.000000             0.000000  
25%       0.100000        0.020000             0.070000  
50%       0.170000        0.070000             0.150000  
75%       0.280000        0.190000             0.330000  
max       1.000000        1.000000             1.000000  

[8 rows x 98 columns]

In [256]:
#Check the attributes of table
ccData.columns

Index(['state', 'communityname', 'population', 'householdsize', 'racepctblack',
       'racePctWhite', 'racePctAsian', 'racePctHisp', 'agePct12t21',
       'agePct12t29', 'agePct16t24', 'agePct65up', 'numbUrban', 'pctUrban',
       'medIncome', 'pctWWage', 'pctWFarmSelf', 'pctWInvInc', 'pctWSocSec',
       'pctWPubAsst', 'pctWRetire', 'medFamInc', 'perCapInc', 'whitePerCap',
       'blackPerCap', 'indianPerCap', 'AsianPerCap', 'OtherPerCap',
       'HispPerCap', 'NumUnderPov', 'PctPopUnderPov', 'PctLess9thGrade',
       'PctNotHSGrad', 'PctBSorMore', 'PctUnemployed', 'PctEmploy',
       'PctEmplManu', 'PctEmplProfServ', 'MalePctDivorce', 'MalePctNevMarr',
       'FemalePctDiv', 'TotalPctDiv', 'PersPerFam', 'PctFam2Par',
       'PctKids2Par', 'PctYoungKids2Par', 'PctTeen2Par', 'PctWorkMomYoungKids',
       'PctWorkMom', 'NumIlleg', 'PctIlleg', 'NumImmig', 'PctImmigRecent',
       'PctImmigRec5', 'PctImmigRec8', 'PctImmigRec10', 'PctRecentImmig',
       'PctRecImmig5', 'PctRecImmig8', 'P

In [301]:
y=ccData.ViolentCrimesPerPop
x=ccData.iloc[:,:ccData.shape[1]-1]

In [258]:
print('All attributes dimenision:',x.shape)
print('Target variables dimenision: ',y.shape)

All attributes dimenision: (1994, 99)
Target variables dimenision:  (1994,)


In [259]:
y.head(5)

0    0.20
1    0.67
2    0.43
3    0.12
4    0.03
Name: ViolentCrimesPerPop, dtype: float64

In [260]:
x.head(5)

state        communityname  population  householdsize  racepctblack  \
0      8         Lakewoodcity        0.19           0.33          0.02   
1     53          Tukwilacity        0.00           0.16          0.12   
2     24         Aberdeentown        0.00           0.42          0.49   
3     34  Willingborotownship        0.04           0.77          1.00   
4     42    Bethlehemtownship        0.01           0.55          0.02   

   racePctWhite  racePctAsian  racePctHisp  agePct12t21  agePct12t29  \
0          0.90          0.12         0.17         0.34         0.47   
1          0.74          0.45         0.07         0.26         0.59   
2          0.56          0.17         0.04         0.39         0.47   
3          0.08          0.12         0.10         0.51         0.50   
4          0.95          0.09         0.05         0.38         0.38   

        ...        NumInShelters  NumStreet  PctForeignBorn  PctBornSameState  \
0       ...                 0.04        0.0            0.12              0.42   
1       ...                 0.00        0.0            0.21              0.50   
2       ...                 0.00        0.0            0.14              0.49   
3       ...                 0.00        0.0            0.19              0.30   
4       ...                 0.00        0.0            0.11              0.72   

   PctSameHouse85  PctSameCity85  PctSameState85  LandArea  PopDens  \
0            0.50           0.51            0.64      0.12     0.26   
1            0.34           0.60            0.52      0.02     0.12   
2            0.54           0.67            0.56      0.01     0.21   
3            0.73           0.64            0.65      0.02     0.39   
4            0.64           0.61            0.53      0.04     0.09   

   PctUsePubTrans  
0            0.20  
1            0.45  
2            0.02  
3            0.28  
4            0.02  

[5 rows x 99 columns]

In [303]:
#Now we are going to drop the 2 identifier attribute 'state' and 'communityname'
x.drop('state', axis=1,inplace= True)
x.drop('communityname',axis=1,inplace=True)
x.head(5)

population  householdsize  racepctblack  racePctWhite  racePctAsian  \
0        0.19           0.33          0.02          0.90          0.12   
1        0.00           0.16          0.12          0.74          0.45   
2        0.00           0.42          0.49          0.56          0.17   
3        0.04           0.77          1.00          0.08          0.12   
4        0.01           0.55          0.02          0.95          0.09   

   racePctHisp  agePct12t21  agePct12t29  agePct16t24  agePct65up  \
0         0.17         0.34         0.47         0.29        0.32   
1         0.07         0.26         0.59         0.35        0.27   
2         0.04         0.39         0.47         0.28        0.32   
3         0.10         0.51         0.50         0.34        0.21   
4         0.05         0.38         0.38         0.23        0.36   

        ...        NumInShelters  NumStreet  PctForeignBorn  PctBornSameState  \
0       ...                 0.04        0.0            0.12              0.42   
1       ...                 0.00        0.0            0.21              0.50   
2       ...                 0.00        0.0            0.14              0.49   
3       ...                 0.00        0.0            0.19              0.30   
4       ...                 0.00        0.0            0.11              0.72   

   PctSameHouse85  PctSameCity85  PctSameState85  LandArea  PopDens  \
0            0.50           0.51            0.64      0.12     0.26   
1            0.34           0.60            0.52      0.02     0.12   
2            0.54           0.67            0.56      0.01     0.21   
3            0.73           0.64            0.65      0.02     0.39   
4            0.64           0.61            0.53      0.04     0.09   

   PctUsePubTrans  
0            0.20  
1            0.45  
2            0.02  
3            0.28  
4            0.02  

[5 rows x 97 columns]

In [262]:
#Now we look into the statistic of every attributes in the Table
x.describe().T

count      mean       std  min     25%    50%     75%  \
population             1994.0  0.057593  0.126906  0.0  0.0100  0.020  0.0500   
householdsize          1994.0  0.463395  0.163717  0.0  0.3500  0.440  0.5400   
racepctblack           1994.0  0.179629  0.253442  0.0  0.0200  0.060  0.2300   
racePctWhite           1994.0  0.753716  0.244039  0.0  0.6300  0.850  0.9400   
racePctAsian           1994.0  0.153681  0.208877  0.0  0.0400  0.070  0.1700   
racePctHisp            1994.0  0.144022  0.232492  0.0  0.0100  0.040  0.1600   
agePct12t21            1994.0  0.424218  0.155196  0.0  0.3400  0.400  0.4700   
agePct12t29            1994.0  0.493867  0.143564  0.0  0.4100  0.480  0.5400   
agePct16t24            1994.0  0.336264  0.166505  0.0  0.2500  0.290  0.3600   
agePct65up             1994.0  0.423164  0.179185  0.0  0.3000  0.420  0.5300   
numbUrban              1994.0  0.064072  0.128256  0.0  0.0000  0.030  0.0700   
pctUrban               1994.0  0.696269  0.444811  0.0  0.0000  1.000  1.0000   
medIncome              1994.0  0.361123  0.209362  0.0  0.2000  0.320  0.4900   
pctWWage               1994.0  0.558154  0.182913  0.0  0.4400  0.560  0.6900   
pctWFarmSelf           1994.0  0.291570  0.204108  0.0  0.1600  0.230  0.3700   
pctWInvInc             1994.0  0.495687  0.178071  0.0  0.3700  0.480  0.6200   
pctWSocSec             1994.0  0.471133  0.173619  0.0  0.3500  0.475  0.5800   
pctWPubAsst            1994.0  0.317778  0.222137  0.0  0.1425  0.260  0.4400   
pctWRetire             1994.0  0.479248  0.167564  0.0  0.3600  0.470  0.5800   
medFamInc              1994.0  0.375677  0.198257  0.0  0.2300  0.330  0.4800   
perCapInc              1994.0  0.350251  0.191109  0.0  0.2200  0.300  0.4300   
whitePerCap            1994.0  0.368049  0.186804  0.0  0.2400  0.320  0.4400   
blackPerCap            1994.0  0.291098  0.171593  0.0  0.1725  0.250  0.3800   
indianPerCap           1994.0  0.203506  0.164775  0.0  0.1100  0.170  0.2500   
AsianPerCap            1994.0  0.322357  0.195411  0.0  0.1900  0.280  0.4000   
HispPerCap             1994.0  0.386279  0.183081  0.0  0.2600  0.345  0.4800   
NumUnderPov            1994.0  0.055507  0.127941  0.0  0.0100  0.020  0.0500   
PctPopUnderPov         1994.0  0.303024  0.228474  0.0  0.1100  0.250  0.4500   
PctLess9thGrade        1994.0  0.315807  0.213360  0.0  0.1600  0.270  0.4200   
PctNotHSGrad           1994.0  0.383330  0.202508  0.0  0.2300  0.360  0.5100   
...                       ...       ...       ...  ...     ...    ...     ...   
PctHousLess3BR         1994.0  0.495186  0.172508  0.0  0.4000  0.510  0.6000   
MedNumBR               1994.0  0.314694  0.255182  0.0  0.0000  0.500  0.5000   
HousVacant             1994.0  0.076815  0.150465  0.0  0.0100  0.030  0.0700   
PctHousOccup           1994.0  0.719549  0.194024  0.0  0.6300  0.770  0.8600   
PctHousOwnOcc          1994.0  0.548686  0.185204  0.0  0.4300  0.540  0.6700   
PctVacantBoarded       1994.0  0.204529  0.217770  0.0  0.0600  0.130  0.2700   
PctVacMore6Mos         1994.0  0.433335  0.188986  0.0  0.2900  0.420  0.5600   
MedYrHousBuilt         1994.0  0.494178  0.232467  0.0  0.3500  0.520  0.6700   
PctHousNoPhone         1994.0  0.264478  0.242847  0.0  0.0600  0.185  0.4200   
PctWOFullPlumb         1994.0  0.243059  0.206295  0.0  0.1000  0.190  0.3300   
OwnOccLowQuart         1994.0  0.264689  0.224425  0.0  0.0900  0.180  0.4000   
OwnOccMedVal           1994.0  0.263490  0.231542  0.0  0.0900  0.170  0.3900   
OwnOccHiQuart          1994.0  0.268942  0.235252  0.0  0.0900  0.180  0.3800   
RentLowQ               1994.0  0.346379  0.219323  0.0  0.1700  0.310  0.4900   
RentMedian             1994.0  0.372457  0.209278  0.0  0.2000  0.330  0.5200   
RentHighQ              1994.0  0.422964  0.248286  0.0  0.2200  0.370  0.5900   
MedRent                1994.0  0.384102  0.213404  0.0  0.2100  0.340  0.5300   
MedRentPctHousInc      1994.0  0.490125  0.169500  0.0 

In [263]:
#Statistics of the Target variables
y.describe()

count    1994.000000
mean        0.237979
std         0.232985
min         0.000000
25%         0.070000
50%         0.150000
75%         0.330000
max         1.000000
Name: ViolentCrimesPerPop, dtype: float64

####1b) Perform standard linear regression on data using the implementation for Ch. 8 of MLA. Compute the RMSE value on the full training data. Also, plot the correlation between the predicted and actual values of the target attribute. Display the obtained regression coefficients (weights). Finally, perform 10-fold cross-validation and compare the cross-validation RMSE to the training RMSE (for cross validation, you may use the KFold module from sklearn.cross_validation).

In [308]:
x=np.array(x)
y=np.array(y)

In [309]:
x.dtype

dtype('O')

In [305]:
np.set_printoptions(precision=2, linewidth=120, suppress=True, edgeitems=7)
x.T*x

TypeError: can't multiply sequence by non-int of type 'float'

In [188]:
x = np.array([np.concatenate((v,[1])) for v in x])


In [189]:
x=np.array(x)
y=np.array(y)

In [229]:
x.shape

(1994, 97)

In [191]:
y.shape

(1994,)

In [237]:
x=np.mat(x)

In [250]:
x

matrix([[0.19, 0.33, 0.02, ..., 0.12, 0.26, 0.2],
        [0.0, 0.16, 0.12, ..., 0.02, 0.12, 0.45],
        [0.0, 0.42, 0.49, ..., 0.01, 0.21, 0.02],
        ..., 
        [0.16, 0.37, 0.25, ..., 0.08, 0.32, 0.18],
        [0.08, 0.51, 0.06, ..., 0.03, 0.38, 0.33],
        [0.2, 0.78, 0.14, ..., 0.11, 0.3, 0.05]], dtype=object)

In [167]:
#Machine Learning in Action, Chapter 8:
def standRegres(xArr,yArr):
    xMat = np.mat(xArr); yMat = np.mat(yArr).T
    xTx = xMat.T*xMat
    if np.linalg.det(xTx) == 0.0:
        print ("This matrix is singular, cannot do inverse")
        return
    ws = xTx.I * (xMat.T*yMat)
    return ws

In [283]:
xMat = mat(x)

NameError: name 'mat' is not defined

In [282]:
x

matrix([[0.19, 0.33, 0.02, ..., 0.12, 0.26, 0.2],
        [0.0, 0.16, 0.12, ..., 0.02, 0.12, 0.45],
        [0.0, 0.42, 0.49, ..., 0.01, 0.21, 0.02],
        ..., 
        [0.16, 0.37, 0.25, ..., 0.08, 0.32, 0.18],
        [0.08, 0.51, 0.06, ..., 0.03, 0.38, 0.33],
        [0.2, 0.78, 0.14, ..., 0.11, 0.3, 0.05]], dtype=object)

In [155]:
xMat.shape

(1994, 98)

In [310]:
tm=np.mat([[0.1,0.11],[0.2,0.22],[0.33,0.333]])

In [311]:
tm.dtype

dtype('float64')

In [272]:
type(tm.dtype)

numpy.dtype

In [205]:
tm.T*tm

matrix([[ 0.1589  ,  0.16489 ],
        [ 0.16489 ,  0.171389]])

In [222]:
tm=x[0]
tm.astype(float)

matrix([[ 0.19,  0.33,  0.02,  0.9 ,  0.12,  0.17,  0.34,  0.47,  0.29,
          0.32,  0.2 ,  1.  ,  0.37,  0.72,  0.34,  0.6 ,  0.29,  0.15,
          0.43,  0.39,  0.4 ,  0.39,  0.32,  0.27,  0.27,  0.36,  0.41,
          0.08,  0.19,  0.1 ,  0.18,  0.48,  0.27,  0.68,  0.23,  0.41,
          0.68,  0.4 ,  0.75,  0.75,  0.35,  0.55,  0.59,  0.61,  0.56,
          0.74,  0.76,  0.04,  0.14,  0.03,  0.24,  0.27,  0.37,  0.39,
          0.07,  0.07,  0.08,  0.08,  0.89,  0.06,  0.14,  0.13,  0.33,
          0.39,  0.28,  0.55,  0.09,  0.51,  0.5 ,  0.21,  0.71,  0.52,
          0.05,  0.26,  0.65,  0.14,  0.06,  0.22,  0.19,  0.18,  0.36,
          0.35,  0.38,  0.34,  0.38,  0.46,  0.25,  0.04,  0.  ,  0.12,
          0.42,  0.5 ,  0.51,  0.64,  0.12,  0.26,  0.2 ,  1.  ,  1.  ]])

In [224]:
tm.T

matrix([[0.19],
        [0.33],
        [0.02],
        [0.9],
        [0.12],
        [0.17],
        [0.34],
        [0.47],
        [0.29],
        [0.32],
        [0.2],
        [1.0],
        [0.37],
        [0.72],
        [0.34],
        [0.6],
        [0.29],
        [0.15],
        [0.43],
        [0.39],
        [0.4],
        [0.39],
        [0.32],
        [0.27],
        [0.27],
        ['0.36'],
        [0.41],
        [0.08],
        [0.19],
        [0.1],
        [0.18],
        [0.48],
        [0.27],
        [0.68],
        [0.23],
        [0.41],
        [0.68],
        [0.4],
        [0.75],
        [0.75],
        [0.35],
        [0.55],
        [0.59],
        [0.61],
        [0.56],
        [0.74],
        [0.76],
        [0.04],
        [0.14],
        [0.03],
        [0.24],
        [0.27],
        [0.37],
        [0.39],
        [0.07],
        [0.07],
        [0.08],
        [0.08],
        [0.89],
        [0.06],
        [0.14],
        [0.13],
        [0.33

In [225]:
tm

matrix([[0.19, 0.33, 0.02, 0.9, 0.12, 0.17, 0.34, 0.47, 0.29, 0.32, 0.2,
         1.0, 0.37, 0.72, 0.34, 0.6, 0.29, 0.15, 0.43, 0.39, 0.4, 0.39,
         0.32, 0.27, 0.27, '0.36', 0.41, 0.08, 0.19, 0.1, 0.18, 0.48, 0.27,
         0.68, 0.23, 0.41, 0.68, 0.4, 0.75, 0.75, 0.35, 0.55, 0.59, 0.61,
         0.56, 0.74, 0.76, 0.04, 0.14, 0.03, 0.24, 0.27, 0.37, 0.39, 0.07,
         0.07, 0.08, 0.08, 0.89, 0.06, 0.14, 0.13, 0.33, 0.39, 0.28, 0.55,
         0.09, 0.51, 0.5, 0.21, 0.71, 0.52, 0.05, 0.26, 0.65, 0.14, 0.06,
         0.22, 0.19, 0.18, 0.36, 0.35, 0.38, 0.34, 0.38, 0.46, 0.25, 0.04,
         0.0, 0.12, 0.42, 0.5, 0.51, 0.64, 0.12, 0.26, 0.2, 1, 1]], dtype=object)